"""add owner_id to todos

Revision ID: fabe0e5c57b1
Revises: afe4612cf184
Create Date: 2026-03-17 10:10:10.466753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fabe0e5c57b1"
down_revision: Union[str, Sequence[str], None] = "afe4612cf184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 加列（允许 NULL，因为旧数据还没有 owner）
    op.add_column("todos", sa.Column("owner_id", sa.Integer(), nullable=True))
    
    # 2. 给旧数据赋默认值（id=1 的用户）
    op.execute("UPDATE todos SET owner_id = 1 WHERE owner_id IS NULL")
    
    # 3. 加外键约束
    op.create_foreign_key(
        "fk_todos_owner_id_users",
        "todos", "users",
        ["owner_id"], ["id"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_column("todos", "owner_id")
    # ### end Alembic commands ###
